### ISSUE TITLE
flaky behavior when subsumption rules get cyclic

### ISSUE THREAD

**Issue by yihozhang** [souffle-lang/souffle#2117]
Hello Souffle developers!

(Below are tested under master branch commit 31aaefe07d6.)

When I was playing around with the subsumption feature introduced in PR #2114, I found the following flaky behavior.

```
.type Id = Num { x : number }
        | Var { v : symbol}
        | Add {e_1 : Id, e_2 :Id}
// .type Id = Num { x : number }
.decl num(r:Id, x:number) btree_delete
// .decl var(r:Id, v:symbol) btree_delete
.decl leader(c:Id, p:Id)

num($Num(1), 1).
num($Num(2), 2).

leader(x, x) :- num(x, _).

num(id2, y) :- num(id1, y), leader(id1, id2).
num(id1, y) <= num(id2, y) :-
  leader(id1, id2).

.output leader
```
This program will yield the following `leader` relation, which is expected (by the `leader(x, x) :- num(x, _).` rule).
```
$Num(1) $Num(1)
$Num(2) $Num(2)
```
However, if I uncomment the declaration of the var relation, which is used nowhere, `leader` becomes an empty relation.

I am not very familiar with debugging Souffle program, but I took a look at the RAM output of the wrong program, which is pasted below. Here is my hypothesis after doing some naive static reasoning: before entering the loop, `num($Num(1), 1).` and `num($Num(2), 2).` are fired, but the `leader` relation is not getting updated. In first iteration of the loop body, the `leader` relation (which is currently empty) is used to update the `num` relation, which does nothing and so `new_num` is empty. This in turn causes the `leader` relation not to update. Therefore, `leader` is empty as well.

<details><summary>RAM output</summary>
<p>

```
PROGRAM
 DECLARATION
  num(r:+:Id,x:i:number) btree_delete
  @delta_num(r:+:Id,x:i:number) 
  @new_num(r:+:Id,x:i:number) 
  @reject_num(r:+:Id,x:i:number) 
  @delete_num(r:+:Id,x:i:number) 
  leader(c:+:Id,p:+:Id) 
  @delta_leader(c:+:Id,p:+:Id) 
  @new_leader(c:+:Id,p:+:Id) 
 END DECLARATION
 SUBROUTINE stratum_0
  DEBUG "num($Num(1),1).\nin file /homes/iws/yz489/conglog/main_naive.dl [10:1-10:17]"
   QUERY
    INSERT (PACK(NUMBER(1),NUMBER(1)), NUMBER(1)) INTO num
   END QUERY
  END DEBUG
  DEBUG "num($Num(2),2).\nin file /homes/iws/yz489/conglog/main_naive.dl [11:1-11:17]"
   QUERY
    INSERT (PACK(NUMBER(1),NUMBER(2)), NUMBER(2)) INTO num
   END QUERY
  END DEBUG
  DEBUG "num(id1,y) <= num(id2,y) :- \n   leader(id1,id2).\nin file /homes/iws/yz489/conglog/main_naive.dl [16:1-17:20]"
   QUERY
    IF ((NOT ISEMPTY(leader)) AND (NOT ISEMPTY(num)))
     FOR t0 IN num
      FOR t1 IN num ON INDEX t1.1 = t0.1
       IF ((NOT (t0.0 = t1.0)) AND (t0.0,t1.0) IN leader)
        INSERT (t0.0, t0.1) INTO @delete_num
   END QUERY
  END DEBUG
  QUERY
   FOR t0 IN @delete_num
    ERASE (t0.0, t0.1) FROM num
  END QUERY
  CLEAR @delete_num
  QUERY
   FOR t0 IN num
    INSERT (t0.0, t0.1) INTO @delta_num
  END QUERY
  QUERY
   FOR t0 IN leader
    INSERT (t0.0, t0.1) INTO @delta_leader
  END QUERY
  LOOP
   DEBUG "num(id2,y) :- \n   num(id1,y),\n   leader(id1,id2).\nin file /homes/iws/yz489/conglog/main_naive.dl [15:1-15:46]"
    QUERY
     IF ((NOT ISEMPTY(@delta_num)) AND (NOT ISEMPTY(leader)))
      FOR t0 IN @delta_num
       FOR t1 IN leader ON INDEX t1.0 = t0.0
        IF ((NOT (t1.1,t0.1) IN num) AND (NOT (t0.0,t1.1) IN @delta_leader))
         INSERT (t1.1, t0.1) INTO @new_num
    END QUERY
   END DEBUG
   DEBUG "num(id2,y) :- \n   num(id1,y),\n   leader(id1,id2).\nin file /homes/iws/yz489/conglog/main_naive.dl [15:1-15:46]"
    QUERY
     IF ((NOT ISEMPTY(num)) AND (NOT ISEMPTY(@delta_leader)))
      FOR t0 IN num
       FOR t1 IN @delta_leader ON INDEX t1.0 = t0.0
        IF (NOT (t1.1,t0.1) IN num)
         INSERT (t1.1, t0.1) INTO @new_num
    END QUERY
   END DEBUG
   CLEAR @delta_num
   DEBUG "num(id1,y) <= num(id2,y) :- \n   leader(id1,id2).\nin file /homes/iws/yz489/conglog/main_naive.dl [16:1-17:20]"
    QUERY
     IF ((NOT ISEMPTY(leader)) AND (NOT ISEMPTY(@new_num)))
      FOR t0 IN @new_num
       FOR t1 IN @new_num ON INDEX t1.1 = t0.1
        IF ((NOT (t0.0 = t1.0)) AND (t0.0,t1.0) IN leader)
         INSERT (t0.0, t0.1) INTO @reject_num
    END QUERY
   END DEBUG
   DEBUG "num(id1,y) <= num(id2,y) :- \n   leader(id1,id2).\nin file /homes/iws/yz489/conglog/main_naive.dl [16:1-17:20]"
    QUERY
     IF (((NOT ISEMPTY(leader)) AND (NOT ISEMPTY(@new_num))) AND (NOT ISEMPTY(num)))
      FOR t0 IN @new_num
       IF EXISTS t1 IN num ON INDEX t1.1 = t0.1 WHERE (t0.0,t1.0) IN leader
        INSERT (t0.0, t0.1) INTO @reject_num
    END QUERY
   END DEBUG
   DEBUG "num(id1,y) <= num(id2,y) :- \n   leader(id1,id2).\nin file /homes/iws/yz489/conglog/main_naive.dl [16:1-17:20]"
    QUERY
     IF ((NOT ISEMPTY(@delta_leader)) AND (NOT ISEMPTY(@new_num)))
      FOR t0 IN @new_num
       FOR t1 IN @new_num ON INDEX t1.1 = t0.1
        IF ((NOT (t0.0 = t1.0)) AND (t0.0,t1.0) IN @delta_leader)
         INSERT (t0.0, t0.1) INTO @reject_num
    END QUERY
   END DEBUG
   DEBUG "num(id1,y) <= num(id2,y) :- \n   leader(id1,id2).\nin file /homes/iws/yz489/conglog/main_naive.dl [16:1-17:20]"
    QUERY
     IF (((NOT ISEMPTY(@delta_leader)) AND (NOT ISEMPTY(@new_num))) AND (NOT ISEMPTY(num)))
      FOR t0 IN @new_num
       IF EXISTS t1 IN num ON INDEX t1.1 = t0.1 WHERE (t0.0,t1.0) IN @delta_leader
        INSERT (t0.0, t0.1) INTO @reject_num
    END QUERY
   END DEBUG
   QUERY
    FOR t0 IN @new_num
     IF (NOT (t0.0,t0.1) IN @reject_num)
      INSERT (t0.0, t0.1) INTO @delta_num
   END QUERY
   CLEAR @reject_num
   CLEAR @new_num
   DEBUG "num(id1,y) <= num(id2,y) :- \n   leader(id1,id2).\nin file /homes/iws/yz489/conglog/main_naive.dl [16:1-17:20]"
    QUERY
     IF (((NOT ISEMPTY(leader)) AND (NOT ISEMPTY(num))) AND (NOT ISEMPTY(@delta_num)))
      FOR t0 IN num
       IF EXISTS t1 IN @delta_num ON INDEX t1.1 = t0.1 WHERE (t0.0,t1.0) IN leader
        INSERT (t0.0, t0.1) INTO @delete_num
    END QUERY
   END DEBUG
   DEBUG "num(id1,y) <= num(id2,y) :- \n   leader(id1,id2).\nin file /homes/iws/yz489/conglog/main_naive.dl [16:1-17:20]"
    QUERY
     IF (((NOT ISEMPTY(@delta_leader)) AND (NOT ISEMPTY(num))) AND (NOT ISEMPTY(@delta_num)))
      FOR t0 IN num
       IF EXISTS t1 IN @delta_num ON INDEX t1.1 = t0.1 WHERE (t0.0,t1.0) IN @delta_leader
        INSERT (t0.0, t0.1) INTO @delete_num
    END QUERY
   END DEBUG
   QUERY
    FOR t0 IN @delete_num
     ERASE (t0.0, t0.1) FROM num
   END QUERY
   CLEAR @delete_num
   DEBUG "leader(x,x) :- \n   num(x,_).\nin file /homes/iws/yz489/conglog/main_naive.dl [13:1-13:27]"
    QUERY
     IF (NOT ISEMPTY(@delta_num))
      FOR t0 IN @delta_num
       IF (NOT (t0.0,t0.0) IN leader)
        INSERT (t0.0, t0.0) INTO @new_leader
    END QUERY
   END DEBUG
   EXIT (ISEMPTY(@delta_num) AND ISEMPTY(@new_leader))
   QUERY
    FOR t0 IN @delta_num
     INSERT (t0.0, t0.1) INTO num
   END QUERY
   QUERY
    FOR t0 IN @new_leader
     INSERT (t0.0, t0.1) INTO leader
   END QUERY
   SWAP (@delta_leader, @new_leader)
   CLEAR @new_leader
  END LOOP
  CLEAR @delta_num
  CLEAR @new_num
  CLEAR @delta_leader
  CLEAR @new_leader
  IO num (IO="file",attributeNames="r\tx",auxArity="0",name="num",operation="output",output-dir=".",params="{\"records\": {}, \"relation\": {\"arity\": 2, \"params\": [\"r\", \"x\"]}}",types="{\"ADTs\": {\"+:Id\": {\"arity\": 3, \"branches\": [{\"name\": \"Add\", \"types\": [\"+:Id\", \"+:Id\"]}, {\"name\": \"Num\", \"types\": [\"i:number\"]}, {\"name\": \"Var\", \"types\": [\"s:symbol\"]}], \"enum\": false}}, \"records\": {}, \"relation\": {\"arity\": 2, \"types\": [\"+:Id\", \"i:number\"]}}")
  IO leader (IO="file",attributeNames="c\tp",auxArity="0",name="leader",operation="output",output-dir=".",params="{\"records\": {}, \"relation\": {\"arity\": 2, \"params\": [\"c\", \"p\"]}}",types="{\"ADTs\": {\"+:Id\": {\"arity\": 3, \"branches\": [{\"name\": \"Add\", \"types\": [\"+:Id\", \"+:Id\"]}, {\"name\": \"Num\", \"types\": [\"i:number\"]}, {\"name\": \"Var\", \"types\": [\"s:symbol\"]}], \"enum\": false}}, \"records\": {}, \"relation\": {\"arity\": 2, \"types\": [\"+:Id\", \"+:Id\"]}}")
 END SUBROUTINE
 BEGIN MAIN
  CALL stratum_0
 END MAIN
END PROGRAM
```

</p>
</details>

**Comment by b-scholz** [comment]
Thanks for trying out subsumption. It is still very much experimental. I will have a look.

**Comment by b-scholz** [comment]
Please can you check that leader is a partial order:
 1. Reflexive 
 2. Antisymmetric
 3. Transitive

if you don’t have these properties, the output will be random.

**Comment by yihozhang** [comment]
Thanks for the quick reply! I think in this example the leader is a partial order, since it's just an identity relation whose domain covers the first column of `num`, but I may misunderstand things.

**Comment by remysucre** [comment]
Is it possible that leaders could not establish reflexivity in time? I think this is what @yihozhang ’s analysis suggests

**Comment by remysucre** [comment]
Changing the subsumption rule to `num(id1, y) <= num(id2, y) :- id1=id2.` works for me, but `num(id1, y) <= num(id2, y) :- id1=id2; leader(id1, id2).` does not.

**Comment by b-scholz** [comment]
This issue should be resolved with the latest PR #2118.

**Comment by b-scholz** [comment]
Please, can you check?

**Comment by yihozhang** [comment]
Thanks for the fix! I'm still having some problems with my real program (where the reported one is derived), but I'm not sure if it's my fault or something. I'll let you know once I figure out.

**Comment by b-scholz** [comment]
Could you find other issues?

**Comment by yihozhang** [comment]
@b-scholz Yes, I found another issue. Could you take a look?

```
.decl eql(a: number, b: number) eqrel
.decl rel(a: number, b: number) btree_delete

rel(1, 2).
rel(1, 3).

eql(x, x) :- rel(x, _).
// eql(1, 1).
eql(2, 3).

rel(a, b) <= rel(c, d) :- eql(a, c), eql(b, d), a <= c, b <= d.

.output rel(IO=stdout)
.output eql(IO=stdout)
```

I expected `rel` to produce only `(1, 3)`. However, it produces both `(1, 2)` and `(1, 3)`. Note that the `eqrel` annotation on `eql` is only to enforce `rel` to be an equivalence relation and a plain `eql` relation yields the same result.

Use `eql(1, 1).` instead of `eql(x, x) :- rel(x, _).` does produce the expected output.
