### ISSUE TITLE
Compilation error in Mac

### ISSUE THREAD

**Issue by siscia** [souffle-lang/souffle#2404]
I got a compilation error while trying to compile on my mac.

The error is:

```
[ 21%] Building CXX object src/CMakeFiles/libsouffle.dir/parser/scanner.cc.o
/Users/siscia/personal/souffle/build/src/parser/scanner.cc:2406:41: error: comparison of integers of different signs: 'unsigned long' and 'int' [-Werror,-Wsign-compare]
        if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I "solved" it with:

```
siscia@b0be83766127 souffle % git diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 15761d4a6..779acc5bf 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -175,7 +175,7 @@ flex_target(scanner parser/scanner.ll ${CMAKE_CURRENT_BINARY_DIR}/parser/scanner
   COMPILE_FLAGS "${SCANNER_COMPILE_FLAGS} -d")

 bison_target(parser parser/parser.yy ${CMAKE_CURRENT_BINARY_DIR}/parser/parser.cc
-             COMPILE_FLAGS "-Wall -Werror -Wno-error=deprecated -Wno-error=other -v -d")
+             COMPILE_FLAGS "-Wall -Wno-error=deprecated -Wno-error=other -v -d")
 add_flex_bison_dependency(scanner parser)


@@ -229,7 +229,7 @@ set_target_properties(compiled PROPERTIES CXX_EXTENSIONS OFF)
 set_target_properties(compiled PROPERTIES POSITION_INDEPENDENT_CODE ON)

 if (NOT MSVC)
-  target_compile_options(libsouffle PUBLIC -Wall -Wextra -Werror -fwrapv)
+  target_compile_options(libsouffle PUBLIC -Wall -Wextra -fwrapv)
 else ()
   target_compile_options(libsouffle PUBLIC /W3 /WX)
 endif ()
 ```

And then rebuilding the cmake and compiling again.

I was using bison `3.8.2` and gcc `12.2`.

I don't think the patch is good enough for a PR, however I open anyway to help fellow souffle users that might don't know what to do.

If you need anything else, please let me know here.

**Comment by quentin** [comment]
Probably fixed by #2299. Please reopen otherwise.

**Comment by qkmaosjtu** [comment]
![image](https://user-images.githubusercontent.com/16631352/236160672-0929519e-9b44-4895-978a-b3bb43c6401f.png)
Although the last commit removed -Werror, I still received the error
