### ISSUE TITLE
Disjunctions in the Body of a Clause

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#54]
Synopsis: extend the syntax of Souffle such that disjunctions in the body of a clause are allowed.

Example:
```
A(x) :- B(x); C(x).
```
The relation `A(x)` receives either the values from `B(x)` or `C(x)`. Above relation relation can be rewritten to:
```
A(x) :- B(x).
A(x) :- C(x). 
```

As a first step, a simple expansion mechanism in the AST is sufficient that translated bodies with disjunction to DNF. The DNF is obtained by repetitive applications of the laws of distributivity and DeMorgan. In a later optimization step, we would need to consider which loop nests can be *fused* to optimize the execution.

**Comment by HerbertJordan** [comment]
I am currently working on this. However, I figured that it is a bit more complicated.

The goal is not only to support disjunctions, but also negations. So, for instance, also something like
```
A(X) :- B(X) , ! ( C(X) ; D(X) )
```
should be supported. 

I am almost done with the DNF expansion of any form, but it still needs some work. For instance, currently the AST is designed in a way that you can negate atoms, but no conditions.

Since modifying the negation to contain either an atom or a condition would require changes in the backend, I will negate the operator in the condition. However, currently the set of supported operators is not closed under negation. For instance, notMatch is not supported. So I will have to add those as well, before being able to finish the DNF part.

Another feature which conflicts with a complex body structure: explicit execution plans. Those will not be supported for anything that is more complex than a conjunction.

**Comment by b-scholz** [comment]
Should we exclude negated disjunctions?

**Comment by HerbertJordan** [comment]
The same problem is on negated conjunctions. The only way to avoid it is to support negation only on the atom level, which could be annoying. Also, such restrictions all seem quite arbitrary.

It is almost done, by supporting all possible combinations. So I'd say we just go for it.

**Comment by b-scholz** [comment]
Great! That is wonderful!

**Comment by HerbertJordan** [comment]
Fixed by 3a2fd8e3c.

**Comment by yanniss** [comment]
I'm still not sure how to use disjunction in rule bodies. The problem is that parentheses don't work for grouping clauses. I want to write a rule:
M(x,y) :- (!H(x) ; J(x)), O(x,y).

The problem is that:
a) adding parentheses to specify precedence (as above) causes the parser to silently fail. No exception, no error report, just return. (Actually this behavior arises in several parse error cases in the current version, so it's probably a more general issue.)
b) eliminating parentheses causes an error. Conjunction associates more closely than disjunction, so the interpretation is that the !H(x) is an entire body by itself, which leaves variables unbound in the head.

The negation in front of H(x) also prevents me from pulling the "!H(x) ; J(x)" into a separate rule.

**Comment by HerbertJordan** [comment]
Right, I build the handling of the resolution of the DNF form in the frontend, but I was not careful enough in designing the grammar in the parser.

I will have a look at it and fix it asap.

**Comment by HerbertJordan** [comment]
I have fixed the bug and issues a pull request. Once it is done, you may try the updated version.

Please let me know if you find any further issues in the supported grammar and/or its semantic. We would like to add such identified problems to our test-case suite.

**Comment by yanniss** [comment]
Awesome! Thanks!!!
I will try as soon as it's merged.

**Comment by HerbertJordan** [comment]
The fix has been merged #101

**Comment by yanniss** [comment]
Thanks! I think this is safe to mark fixed, though I'm sure I'll keep kicking the tires (inadvertently :-)).
